# Spring properties
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:BsvztR7c5Xj9RWKW@cluster0.3cxh2.mongodb.net/artefck?retryWrites=true&w=majority
  application:
    name: user-service  # Service registers under this name
  servlet:
    multiplart:
      max-file-size: 4MB   
      max-request-size: 4MB

endpoints:
  health:
    enabled: yes
  shutdown:
    enabled: yes

management:
    context-path: /admin
logging:
  level:
    org:
      springframework:
        web:
          client: DEBUG

# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port

